config/routes.rb
Restaurant::Application.routes.draw do
  resources :ticketitems

  resources :checkouts

  resources :tickets

  resources :menus

end

app/models/ticket.rb
class Ticket < ActiveRecord::Base
  has_many :ticketitems
  has_many :menus, through: :ticketitems
   attr_accessible :name, :price, :quantity, :subtotal

   validates :name, :price, :quantity, presence: true

  before_save do
    subtotal
  end
  def subtotal
  self.subtotal = self.quantity * self.price
    end
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  # GET /tickets
  # GET /tickets.json
  def index
    @tickets = Ticket.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tickets }
    end
  end

  # GET /tickets/1
  # GET /tickets/1.json
  def show
    @ticket = Ticket.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @ticket }
    end
  end

  # GET /tickets/new
  # GET /tickets/new.json
  def new
    @ticket = Ticket.new

       respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @ticket }
    end
  end

  # GET /tickets/1/edit
  def edit
    @ticket = Ticket.find(params[:id])
  end

  # POST /tickets
  # POST /tickets.json
  def create
    @ticketitem = Ticketitem.new(params[:ticketitem])

    respond_to do |format|
      if @ticket.save
        format.html { redirect_to @ticket, notice: 'Ticket was successfully created.' }
        format.json { render json: @ticket, status: :created, location: @ticket }
      else
        format.html { render action: "new" }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /tickets/1
  # PUT /tickets/1.json
  def update
    @ticket = Ticket.find(params[:id])

    respond_to do |format|
      if @ticket.update_attributes(params[:ticket])
        format.html { redirect_to @ticket, notice: 'Ticket was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tickets/1
  # DELETE /tickets/1.json
  def destroy
    @ticket = Ticket.find(params[:id])
    @ticket.destroy

    respond_to do |format|
      format.html { redirect_to tickets_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/views/tickets/_form.html.erb
<%= form_for(@ticket) do |f| %>
  <% if @ticket.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ticket.errors.count, "error") %> prohibited this ticket from being saved:</h2>

      <ul>
      <% @ticket.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
      <%= f.collection_select(:name,Menu.all,:name,:name) %>

  </div>
  <div class="field">
    <%= f.label :price %><br />
      <%= f.collection_select(:price,Menu.all,:price,:price) %>
  </div>
  <div class="field">
    <%= f.label :quantity %><br />
    <%= f.text_field :quantity %>
  </div>
  <div class="field">
    <%= f.hidden_field :subtotal, :value => "subtotal" %>
    <%= f.hidden_field :subtotal, :value => "subtotal" %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tickets/edit.html.erb
<h1>Editing ticket</h1>

<%= render 'form' %>

<%= link_to 'Show', @ticket %> |
<%= link_to 'Back', tickets_path %>

app/views/tickets/index.html.erb
<h1>Listing tickets</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Price</th>
    <th>Quantity</th>
    <th>Subtotal</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @tickets.each do |ticket| %>
  <tr>
    <td><%= ticket.name %></td>
    <td><%= number_to_currency(ticket.price) %></td>
    <td><%= ticket.quantity %></td>
    <td><%= number_to_currency(ticket.subtotal) %></td>
    <td><%= link_to 'Add Item', new_ticketitem_path() %></td>
    <td><%= link_to 'Show', ticket %></td>
    <td><%= link_to 'Edit', edit_ticket_path(ticket) %></td>
    <td><%= link_to 'Destroy', ticket, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Ticket', new_ticket_path %>

app/views/tickets/new.html.erb
<h1>New ticket</h1>

<%= render 'form' %>

<%= link_to 'Back', tickets_path %>

app/views/tickets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @ticket.name %>
</p>

<p>
  <b>Price:</b>
  <%= @ticket.price %>
</p>

<p>
  <b>Quantity:</b>
  <%= @ticket.quantity %>
</p>

<p>
  <b>Subtotal:</b>
  <%= @ticket.subtotal %>
</p>
<% @ticket.ticketitems.each do |ticketitem| %>
    <tr>
      <td><%= ticketitem.kitchen_line_status %></td>
      <td><%= ticketitem.item.item_name %></td>
      <td><%= ticketitem.quantity %></td>
      <td><%= number_to_currency(ticketitem.ticket_line_subtotal) %></td>
        </tr>
    <%end%>
<%= link_to 'Edit', edit_ticket_path(@ticket) %> |
<%= link_to 'Back', tickets_path %>