config/routes.rb
Restaurant::Application.routes.draw do
  resources :ticketitems

  resources :checkouts

  resources :tickets

  resources :menus

end

app/models/ticketitem.rb
class Ticketitem < ActiveRecord::Base
  belongs_to :ticket
  belongs_to :menu
  attr_accessible :integer, :name, :name_id, :price, :quantity, :subtotal, :ticket, :ticket_id

  before_save do
    line_total
  end

  def line_total
    self.subtotal= quantity * menu.price
  end
  end

app/controllers/ticketitems_controller.rb
class TicketitemsController < ApplicationController
  # GET /ticketitems
  # GET /ticketitems.json
  def index
    @ticketitems = Ticketitem.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @ticketitems }
    end
  end

  # GET /ticketitems/1
  # GET /ticketitems/1.json
  def show
    @ticketitem = Ticketitem.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @ticketitem }
    end
  end

  # GET /ticketitems/new
  # GET /ticketitems/new.json
  def new
    @ticketitem = Ticketitem.new
    #@ticketitem.ticket_id=params[:ticket]

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @ticketitem }
    end
  end

  # GET /ticketitems/1/edit
  def edit
    @ticketitem = Ticketitem.find(params[:id])
  end

  # POST /ticketitems
  # POST /ticketitems.json
  def create
    @ticketitem = Ticketitem.new(params[:ticketitem])

    respond_to do |format|
      if @ticketitem.save
        format.html { redirect_to @ticketitem, notice: 'Ticketitem was successfully created.' }
        format.json { render json: @ticketitem, status: :created, location: @ticketitem }
      else
        format.html { render action: "new" }
        format.json { render json: @ticketitem.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /ticketitems/1
  # PUT /ticketitems/1.json
  def update
    @ticketitem = Ticketitem.find(params[:id])

    respond_to do |format|
      if @ticketitem.update_attributes(params[:ticketitem])
        format.html { redirect_to @ticketitem, notice: 'Ticketitem was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @ticketitem.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ticketitems/1
  # DELETE /ticketitems/1.json
  def destroy
    @ticketitem = Ticketitem.find(params[:id])
    @ticketitem.destroy

    respond_to do |format|
      format.html { redirect_to ticketitems_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/ticketitems_helper.rb
module TicketitemsHelper
end

app/views/ticketitems/_form.html.erb
<%= form_for(@ticketitem) do |f| %>
  <% if @ticketitem.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ticketitem.errors.count, "error") %> prohibited this ticketitem from being saved:</h2>

      <ul>
      <% @ticketitem.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <div class="field">
      <%= f.hidden_field(:ticket_id) %>
    </div>

  <div class="field">
    <%= f.label :ticket_id %><br />
      <%= f.collection_select(:ticket_id,Ticket.all,:id,:id) %>
  </div>
  <div class="field">
    <%= f.hidden_field :ticket %>
    <%= f.hidden_field :ticket %>
  </div>
  <div class="field">
    <%= f.hidden_field :name_id %>
    <%= f.hidden_field :name_id %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.collection_select(:name,Menu.all,:id,:name) %>
  </div>
  <div class="field">
    <%= f.hidden_field :integer %>
    <%= f.hidden_field :integer %>
  </div>
  <div class="field">
    <%= f.label :price %><br />
    <%= f.collection_select(:price,Menu.all,:price,:price) %>
  </div>
  <div class="field">
    <%= f.label :quantity %><br />
    <%= f.text_field :quantity %>
  </div>
  <div class="field">
    <%= f.hidden_field :subtotal %>
    <%= f.hidden_field :subtotal %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/ticketitems/edit.html.erb
<h1>Editing ticketitem</h1>

<%= render 'form' %>

<%= link_to 'Show', @ticketitem %> |
<%= link_to 'Back', ticketitems_path %>

app/views/ticketitems/index.html.erb
<h1>Adding a new item</h1>

<table>
  <tr>
    <th>Ticket</th>
    <th>Ticket</th>
    <th>Name</th>
    <th>Name</th>
    <th>Integer</th>
    <th>Price</th>
    <th>Quantity</th>
    <th>Subtotal</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @ticketitems.each do |ticketitem| %>
  <tr>
    <td><%= ticketitem.ticket_id %></td>
    <td><%= ticketitem.ticket %></td>
    <td><%= ticketitem.name_id %></td>
    <td><%= ticketitem.name %></td>
    <td><%= ticketitem.integer %></td>
    <td><%= number_to_currency(ticketitem.price) %></td>
    <td><%= ticketitem.quantity %></td>
    <td><%= number_to_currency(ticketitem.subtotal) %></td>
    <td><%= link_to 'Show', ticketitem %></td>
    <td><%= link_to 'Edit', edit_ticketitem_path(ticketitem) %></td>
    <td><%= link_to 'Destroy', ticketitem, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Ticketitem', new_ticketitem_path %>

app/views/ticketitems/new.html.erb
<h1>New ticketitem</h1>

<%= render 'form' %>

<%= link_to 'Back', ticketitems_path %>

app/views/ticketitems/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Ticket:</b>
  <%= @ticketitem.ticket.id %>
</p>

<p>
  <b>Ticket:</b>
  <%= @ticketitem.ticket %>
</p>

<p>
  <b>Name:</b>
  <%= @ticketitem.name_id %>
</p>

<p>
  <b>Name:</b>
  <%= @ticketitem.name %>
</p>

<p>
  <b>Integer:</b>
  <%= @ticketitem.integer %>
</p>

<p>
  <b>Price:</b>
  <%= @ticketitem.price %>
</p>

<p>
  <b>Quantity:</b>
  <%= @ticketitem.quantity %>
</p>

<p>
  <b>Subtotal:</b>
  <%= @ticketitem.subtotal %>
</p>


<%= link_to 'Edit', edit_ticketitem_path(@ticketitem) %> |
<%= link_to 'Back', ticketitems_path %>