config/routes.rb
Restaurant::Application.routes.draw do
  resources :ticketitems

  resources :checkouts

  resources :tickets

  resources :menus

end

app/models/checkout.rb
class Checkout < ActiveRecord::Base
   attr_accessible :kitchen_status, :paid_status, :subtotal, :tax, :ticket_id, :total

   validates :kitchen_status, :paid_status, :subtotal, :tax, :ticket_id, :total, presence: true

   before_save do
     total
   end

  def total
    self.total = self.subtotal + self.tax
  end

  def tax
    self.tax = self.subtotal * 0.0825
  end
end

app/controllers/checkouts_controller.rb
class CheckoutsController < ApplicationController
  # GET /checkouts
  # GET /checkouts.json
  def index
    @checkouts = Checkout.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @checkouts }
    end
  end

  # GET /checkouts/1
  # GET /checkouts/1.json
  def show
    @checkout = Checkout.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @checkout }
    end
  end

  # GET /checkouts/new
  # GET /checkouts/new.json
  def new
    @checkout = Checkout.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @checkout }
    end
  end

  # GET /checkouts/1/edit
  def edit
    @checkout = Checkout.find(params[:id])
  end

  # POST /checkouts
  # POST /checkouts.json
  def create
    @checkout = Checkout.new(params[:checkout])

    respond_to do |format|
      if @checkout.save
        format.html { redirect_to @checkout, notice: 'Checkout was successfully created.' }
        format.json { render json: @checkout, status: :created, location: @checkout }
      else
        format.html { render action: "new" }
        format.json { render json: @checkout.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /checkouts/1
  # PUT /checkouts/1.json
  def update
    @checkout = Checkout.find(params[:id])

    respond_to do |format|
      if @checkout.update_attributes(params[:checkout])
        format.html { redirect_to @checkout, notice: 'Checkout was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @checkout.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /checkouts/1
  # DELETE /checkouts/1.json
  def destroy
    @checkout = Checkout.find(params[:id])
    @checkout.destroy

    respond_to do |format|
      format.html { redirect_to checkouts_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/checkouts_helper.rb
module CheckoutsHelper
end

app/views/checkouts/_form.html.erb
<%= form_for(@checkout) do |f| %>
  <% if @checkout.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@checkout.errors.count, "error") %> prohibited this checkout from being saved:</h2>

      <ul>
      <% @checkout.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :ticket_id %><br />
    <%= f.collection_select(:ticket_id,Ticket.all,:id,:id) %>
  </div>
  <div class="field">
    <%= f.label :subtotal %><br />
      <%= f.collection_select(:subtotal,Ticket.all,:subtotal,:subtotal) %>
  </div>
  <div class="field">
    <%= f.label :tax %><br />
    <%= f.text_field :tax %>
  </div>
  <div class="field">
    <%= f.label :total %><br />
    <%= f.text_field :total %>
  </div>
  <div class="field">
    <%= f.label :kitchen_status, "Food Served" %><br />
    <%= f.check_box :kitchen_status %>
  </div>
  <div class="field">
    <%= f.label :paid_status, "Check Paid" %><br />
    <%= f.check_box :paid_status %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/checkouts/edit.html.erb
<h1>Editing checkout</h1>

<%= render 'form' %>

<%= link_to 'Show', @checkout %> |
<%= link_to 'Back', checkouts_path %>

app/views/checkouts/index.html.erb
<h1>Listing checkouts</h1>

<table>
  <tr>
    <th>Ticket</th>
    <th>Subtotal</th>
    <th>Tax</th>
    <th>Total</th>
    <th>Kitchen status</th>
    <th>Paid status</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @checkouts.each do |checkout| %>
  <tr>
    <td><%= checkout.ticket_id %></td>
    <td><%= number_to_currency(checkout.subtotal) %></td>
    <td><%= checkout.tax %></td>
    <td><%= number_to_currency(checkout.total) %></td>
    <td><%= checkout.kitchen_status %></td>
    <td><%= checkout.paid_status %></td>
    <td><%= link_to 'Show', checkout %></td>
    <td><%= link_to 'Edit', edit_checkout_path(checkout) %></td>
    <td><%= link_to 'Destroy', checkout, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Checkout', new_checkout_path %>

app/views/checkouts/new.html.erb
<h1>New checkout</h1>

<%= render 'form' %>

<%= link_to 'Back', checkouts_path %>

app/views/checkouts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Ticket:</b>
  <%= @checkout.ticket_id %>
</p>

<p>
  <b>Subtotal:</b>
  <%= @checkout.subtotal %>
</p>

<p>
  <b>Tax:</b>
  <%= @checkout.tax %>
</p>

<p>
  <b>Total:</b>
  <%= @checkout.total %>
</p>

<p>
  <b>Kitchen Status:</b>
  <%= @checkout.kitchen_status %>
</p>

<p>
  <b>Paid status:</b>
  <%= @checkout.paid_status %>
</p>


<%= link_to 'Edit', edit_checkout_path(@checkout) %> |
<%= link_to 'Back', checkouts_path %>